# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba1c22e2b72d843c0bf67b84bbb32fe8f7a68f1c2c281c0ab79387e50a37cd0ca31c70cc7cdab13f65b60f9a4be55ce9a06ac7c06267bbdd38d071b78e4d27fb

test:
  secret_key_base: be3bf75843b3cfd940e8f373f4bb5e57dec71930a7158c048dfe718e5de6f6ab049cde63a2c33c812d5b62802cba69ab8f18692cdbb00839bb5b7d7004b496d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
