var main = function () {
	$('.romancebtn').click(function () {
		markovDict={
			'Daffodildo': [null],
			'Wicker': ['Palace'],
			'for': ['Tomorrow', 'Ninety', 'Dr.', 'Loving', 'Luv', 'Maggie', 'Her'],
			'Jenny': ['Jonestown'],
			'Truckee': ['Love'],
			'Bacon': [null],
			'Paloma': ['the'],
			'Autumn': ['Wind'],
			'Pinkish': ['Honeysuckle'],
			'Widows': [null],
			'Sandy': ['Muff'],
			'Wordsmiths': ['in'],
			'Flower': ['Whispers'],
			'Gables': [null],
			'Richard': ['Ramirez'],
			'Doctor': ['Nate', 'For'],
			'Lotto': ['Lita'],
			'Purple': ['Letters'],
			'Gentleman': ['of'],
			'Madly': ['Viking'],
			'True': ['By'],
			'Luxury': [null],
			'Finding': ['Ian'],
			"Mom's": ['Main'],
			'Pirate': ['Crabs', null, 'and'],
			'Shoulders': [null],
			'cover)': [null],
			'Gadget': [null],
			'Ruff': [null],
			'Game': [null],
			'Homes': [null],
			'Anonymous': ['Miss'],
			'Humans': [null],
			'Every': ["Woman's", 'Breath', 'Move'],
			'Capturing': ['Cleo'],
			'Me': ['First', null, 'Tender', null, '...', 'Only'],
			'Eden': [null, null],
			'Home-Grown': ['Husband'],
			'into': ['Spring'],
			"Woman's": ['Fantasy'],
			'Kentucky': ['Heat'],
			'Past': [null],
			'Wicked': ['Cute', 'Is', 'Ways', 'Time', 'Loving', 'To', null],
			'Tempted': ['By'],
			'Mr': ['Reno'],
			'Wannabe': ['Heights'],
			'Triumph': [null],
			'Leather': ['Lather', 'Ride', 'Rip', 'Roads', null],
			'My': ['Heart', 'Trotsky', 'Patch', 'Youth', 'Tree', 'Akimbo', 'Groin', 'Queen', 'Face', 'Equator', 'Spine', 'Tail', 'Mind', 'Command', 'Baby?', 'Flesh', 'Arms', 'Lady', 'Desire', 'Brother', "Lady's", 'Wildest', 'Bed', 'Sexiest', 'Mom'],
			'Jezabel': [null],
			'Jonestown': [null],
			'Riverboat': ['Seduction'],
			'author': ['than'],
			'Love': ['Canal', 'Nothing!', null, null, 'Bomb', 'Canal', 'Digit', 'in', null, 'Songs', 'Poem', 'Me', null],
			'Loner': [null],
			'Midnight': [null],
			'Twenty-Third': ['Man'],
			'Spaces': [null],
			'Female': ['Intelligence'],
			'Intern,': ['Turn,'],
			'(by': ['a'],
			'Limb': [null],
			'Halfway': ['to'],
			'Engagement': [null],
			'Arms': [null, null, null, null],
			'Penelope’s': ['Bathroom'],
			'Bride': ['Said,', 'Said,', null, null, null, null, null, null, null, 'of', null, null, 'Sale', 'And', null, 'Fair', null, null, null],
			'Logic': [null, null],
			'Diaries': [null],
			'Tenderly,': ['Edward'],
			'Star': ['Daughters', null],
			'French': ['Loaf'],
			'Upon': ['a'],
			'Phallus’': ['Restaurant'],
			'Imagine': ['Maggie'],
			'Strong': ['and'],
			'Quimby': ['Heights'],
			'Arch': ["Enemy's"],
			'Lolitass': [null],
			'Plumber': [null],
			'Bondage': [null],
			'Bone': [null],
			'Dragon': ['Sooth'],
			'Moonlight': [null, null],
			'Ranger': [null, 'and'],
			'Horizon': [null],
			'Rocinante': [null],
			'Bob': [null, 'Dole'],
			'Popcorn': ['Born'],
			'Adams': [null],
			'Toils': ['of'],
			'Geese': [null],
			'(doctor': ['on'],
			'Midsummer': ["Night's"],
			'to': ['Find', 'Remember', 'Eternity', 'a', 'Thrill', '5', 'a', 'Marry', 'the', 'Hold', 'Wed', 'the', 'Heaven', 'Fall', 'Delia', 'Tangle'],
			'Placemats': [null],
			'Thinks': [null],
			'Lovers': [null],
			'Catholic': ['Cowgirls', 'Quilt'],
			'For': ['Her', 'Odessa', 'Keeps', 'Her', 'Seduction', 'A', 'Real', 'A', 'Real?'],
			'Spirits': [null],
			'Belongs': [null],
			'Cien': ['Fuegos'],
			'Cthulhu': [null],
			'Sanguine': [null, null],
			'Cabaña': [null, null],
			'He-licks-her': [null],
			'Reader': [null],
			'Paj': [null],
			'Good': ['Girls', null, 'Turn'],
			'Mystical': ['Union'],
			'Garden': [null, 'of'],
			'Stuffers': [null],
			'Kitty': ['Litter', 'Tonic', null],
			'Yanking': ['My'],
			'Touching': ['Evil'],
			'Amy': ['Sanguine'],
			'Hotshot': [null],
			'Hole': [null, null, 'in'],
			'Hold': [null],
			'Catch': ['of'],
			'Ultimatum': [null],
			'Wide': [null, 'Open'],
			"Viking's": ['Woman'],
			'Name': ['Only'],
			'Tree': [null, null],
			'Ashes': ['in'],
			'Flame': [null],
			"Playboy's": ['Office'],
			'Christmas': [null],
			'Chelsea': ['Fortress'],
			'Own': ['Baby'],
			'Campaign': [null, null],
			'Bouquet': [null],
			'Ladybird': [null],
			'Sack': [null],
			'Aroma': [null],
			'Rouge': [null],
			'Rough': ['Wrangler,'],
			'Roads': [null],
			'Story': [null],
			'Tail': [null, null],
			'Better': [null, 'Than'],
			"Nanny's": ['Secret'],
			'Way': [null, 'to', 'to'],
			"Librarian's": ['Secret'],
			'Clover': [null],
			'Temporary': ['Mistress', null, 'Marriage'],
			'Licks': [null],
			'May': ['Hem'],
			'Wrench': [null],
			'Path': [null],
			'Oyster': [null],
			'Man': ['Hole', 'Lot', 'With', null, 'Answers', 'Alone', null, 'With', null, 'in', 'In'],
			'Eligible': ['Golddiggers', 'Texan'],
			'Lawn': [null],
			'Vaseline': ['on'],
			'Liquid': ['Kitty', 'Leather', 'Radiant'],
			'Silence': [null],
			'Fuegos': [null],
			'Coy': [null],
			'Riviera': [null],
			'Jewel': [null],
			'Sale': [null],
			'Ms.': ['Dialed', 'Taken'],
			'Rosemary’s': ['Booby'],
			'Act': [null],
			'Sunset': ['Bird'],
			'Occasion': ['Alice'],
			'First': ['Cafe'],
			'Pillow': [null],
			'Shark': [null],
			'Mini': ['Bar'],
			'Ten': [null],
			'Confessa': [null],
			'Dole': ['and'],
			'Mind': [null],
			'Mine': [null, null],
			'Todd': ['By'],
			'Cleo': [null],
			'Cafe': [null, null],
			'Substitute': ['Father'],
			'Border': ['Hostage'],
			'What': ['the', 'If', 'She'],
			'Cathouse': [null],
			'Funny': ['Thing'],
			'Closet': ['Palace', null],
			'Pregnant!': [null],
			'Mia': ['Fallow'],
			'Lava': [null],
			'Does': ['It'],
			'Foxy': ['by'],
			'Twins': [null],
			'Encino': [null],
			'Fetish': [null],
			'Sin': [null, 'Thesis', null, null, null],
			'Digit': [null],
			'Diamond': ['in'],
			'Possession': [null],
			'Whiled': [null],
			'Around': ['with'],
			'Tool': [null],
			'Pacific': ['Heights'],
			'Took': ['the'],
			'Not-So-Little': ['Secret'],
			'Allen’s': ['Woody'],
			"What's": ['Your'],
			'Malady': [null],
			'Organ': ['Donut', 'Meet', 'Trove'],
			'Penis': ['Envoy'],
			'Cool': ['Under'],
			'Lady': [null, null, null, 'Wayward', null, null],
			'Magma': ['Radiant'],
			'Magic': ['in', null],
			'Radiant': [null, null, 'Fire'],
			'Nate': [null],
			'Mrs.': ['Richard'],
			'Feast': [null],
			'Chuck': ['Driver'],
			'Judy': [null],
			'Undone': [null],
			'Mogul': [null],
			'Contrary': ['Beauty'],
			'Lollytart': [null, null],
			'by': ['Proxy'],
			'Mistake': [null, null],
			'Soft': ['Shoulders', 'Place'],
			'Code': ['Redhead'],
			'Bachelors:': ['Stone'],
			'Inspire': ['Fire'],
			'Potter': [null],
			'Lipstuck': [null],
			'Thesis': [null],
			'Café': [null],
			'Trust': [null, null],
			'Brother': ['Michael'],
			'Priscilla': ['con', 'the'],
			'Tomorrow': [null],
			'Perfect': ['Raspberry', 'Sin', 'Wife', '(doctor'],
			'Nymph': [null],
			'Two': [null, 'Bachelors', 'to'],
			'Anyone': [null],
			'Easy': ['Seed'],
			'Under': ['the', 'the', 'Fire'],
			'Cupids': [null],
			'Hidden': ['Star'],
			'Naïveté': [null, null],
			'Truffles': [null],
			'Wrongstockings': [null],
			'Kissed-Off': [null],
			'Nest': [null],
			'Sensuous': ['Burgundy'],
			'Coming': ['Leaves'],
			'Restaurant': [null],
			'Assets': [null],
			'Plum': ['and'],
			'Trotter': [null],
			'Oriface': [null],
			'Navel': ['Grazing'],
			'Ramirez': [null],
			'Tempting': ['Tess'],
			'Spontaneous': ['Combustion'],
			'Wolf': [null, 'at'],
			"Wycliff's": ['Campaign'],
			'Tongue': ['Dancing', 'in'],
			"Stranger's": ['Caress'],
			'Menagerie': [null, 'à'],
			'Crowd': ['Pleasers'],
			'Tiffany': ['Dreamfeather'],
			'Conundrum': [null],
			'Mauve': [null, 'Lava', 'Suave'],
			'Rip': [null],
			'Crown': ['Jewel'],
			'Rid': ['of'],
			'Divine': [null],
			'Heels': [null],
			'Included': [null],
			'Royal': ['Tease'],
			'Away': [null],
			'Ways': [null],
			'Wildebeest': [null],
			'inHeat': [null],
			'Paradise': [null],
			'Afirmable': ['MR.'],
			'Public': ['Affair'],
			'Hun': [null],
			'Choice': [null],
			'Dark': [null],
			'Fall': ['In', null],
			'Hemi': ['More'],
			'A': ['Chance', 'Feather', 'Freud', 'Stranger', 'Touch', 'Playboy', 'Man', 'Very', 'Night', 'Mission', 'Bride', 'Touch', 'Reluctant', 'Montana', 'Rake', 'Little', 'Midsummer', 'Funny', 'Gentleman', 'Taste', "Stranger's", 'Stetson', 'Reckless', 'Month', 'Lady', 'Breath', 'Touch', 'Taste', 'Well', 'Ghost', 'Little', 'Comfortable', 'Soft', 'Debt', 'Little'],
			'Dare': ['Demeanor', null, 'Demeanor'],
			'Calico': ['Mountain'],
			'Attila': ['the'],
			"Boss's": ['Baby'],
			"Aphrodite's": ['Passion'],
			"Groom's": ['Stand-In'],
			'Will': ['Father'],
			'Crustacean': ['Prince', 'Prince'],
			'Barleycorn': [null],
			'Hunk': ['and'],
			'Dirty': ['Little'],
			'Passionate': ['Captivity', 'Pirate'],
			'Wild': ['Wager', 'Side', 'West', 'Delight', 'Scottish', 'Ride', null, 'About'],
			'Husband': [null, 'on', 'From', 'Not', null, 'For', 'List', 'Test', null],
			'Widow': [null, null],
			'Single,': ['Sexy'],
			'All': [null, 'the', 'Night'],
			'Passages': ['of'],
			'Mommy': ['And', 'and'],
			'Toupee': [null],
			'Private': ['Lessons', 'Investigations'],
			'Walk': ['on'],
			'Slipper': [null],
			'Pane': [null],
			'Pang': [null],
			'Mayhem': [null],
			'Mist': ['on'],
			'Scandal': [null, null],
			'Yankee': ['on'],
			'Miss': [null, 'Demeanor', 'Management', 'Innocent?', 'Adams', 'Tibbles'],
			'Wanton': ['Scholar', 'Won', 'Angel'],
			'Canal': [null, 'Story'],
			'Do!': [null],
			'West': [null, 'Wife'],
			'Bridegroom': [null],
			'Used-to-Be': ['Lovers'],
			'Mr.': ['Ducky', "Hyde's", 'Right', 'Right'],
			'Swamp': ['Secrets'],
			'Rich': [null],
			'Lovely': ['Lovely', 'Two'],
			'Full': ['Moon', null],
			'Run': ['Happiness'],
			'Hank’s': ['Gadget'],
			'Evil': [null],
			'Baring': ['It'],
			'Loins’': ['Logic'],
			'Irvine': ['Swan'],
			'Chance': ['Mating', null, 'Café'],
			'Watch': ['Me'],
			'Blackmailed': ['Bridegroom'],
			'Nowhere': [null],
			"Night's": ['Madness'],
			'Trois': [null],
			'Leaves': [null],
			'Meow': ['Meow', null],
			'Millionaire': ['Takes'],
			'Well': ['Pleasured'],
			'Dog': [null, 'Mountain'],
			'Without': ['Love'],
			'Prescribes': ['...'],
			'$4.98': ['Daddy'],
			'Green': ['Gables'],
			'Wellborne': [null, null],
			'Demand': [null],
			'Ville': [null],
			'Mirrors': [null],
			'Memoirs': ['of'],
			'Delia': [null],
			'Engaged': [null],
			'Prawn': ['Kiss', 'Love', null],
			'Bradley': [null],
			'Mantra': [null],
			'Fair': ['Moan', 'and', null],
			'Tender': ['Loving', null, 'Kisses', null, 'Triumph'],
			"King's": ['Bride'],
			'Witness': [null],
			'Clothing': [null],
			'Temptation': [null, null],
			'Hide': ['and'],
			'Da': ['Bomb'],
			'Love?': [null],
			'Transparent': ['Desires'],
			'Keeping': ['Caroline'],
			'Kathy': [null],
			'Stetson': ['On'],
			'Punch': [null],
			'Toboso': [null],
			'Jack': [null],
			'Wed!': [null],
			'King': ['Conundrum'],
			'Bar': [null],
			'(Almost)': ['Got'],
			'Alice': ['B.', null],
			'Phonebook': ['Diary'],
			'Lingerie': ['Menagerie'],
			'Outrageous': ['Desire'],
			'Loves': [null],
			'Making': ['Mr.'],
			'Sultry': [null],
			'Loaf': [null],
			'Etiquette': [null],
			'Bare': ['Hole'],
			'Granny’s': ['Fanny'],
			'Missle': ['Morning'],
			'Drive,': ['She'],
			'Moonlighting': [null],
			'Degree': [null],
			'Half-Breed': [null],
			'Runaway': ['Bridesmaid'],
			'Grazing': [null],
			'Lessons': [null, null],
			'Poem': [null],
			'Crotchwalk': [null],
			'Maternal': ['Instinct'],
			'There': ['to'],
			'Thursday': [null],
			'Venetian': ['Sack'],
			'Had': ['a', 'to'],
			'Married!': [null],
			'Going': ['...', '...'],
			'Virgin': ['&', null, null, 'and', null, 'in', null, 'Mistress', null],
			'Bad,': ['and'],
			'Redhead': [null],
			"Temperature's": ['Rising'],
			'Deviant': [null],
			'More': [null, 'Juice', 'Than'],
			'Eternity': [null],
			'Lowie': ['Realm'],
			'Gland': [null],
			'Driver': [null],
			'Sins': ['of'],
			'Moment': [null],
			'Rancho': ['Fiesto'],
			'Joe': ['Cuzzi'],
			'Loinsome': ['Dove'],
			'Date': [null],
			'Sexy': ['...', null],
			'Dove': ['Punch', null],
			'Substance': [null],
			'Ulti-Mate': [null],
			'Getting': ['Rid'],
			'Trove': [null, null, null],
			'Face': [null],
			'Luck': [null, 'Wedding'],
			'in': ['Wonderland', 'the', 'Love', 'the', 'the', 'the', 'the', 'Napa', 'One', 'Chic', 'a', 'the', 'Pursuit', 'His', 'Waiting', 'a', 'California', 'Heaven', 'the', 'the', 'Texas', 'My'],
			'Command': [null],
			'Jalapeño': ['Fire'],
			'Yangtze': [null],
			'Songs': [null],
			'Tempt': ['a'],
			'Palace': [null, null, null],
			'Picnic': [null],
			"Can't": ['Resist'],
			'Nascar': ['Wives'],
			'Tide': ['at'],
			'Juice': ['From'],
			'Tranny': ['Hall'],
			'Azerbaijani': ['Picnic'],
			'Tan': [null],
			'Our': ['Beds'],
			'Out': [null],
			'Savage': ['Innocence', 'Moon', 'Persuasion', 'Love'],
			'Beds': ['Together'],
			'Norse’s': ['Mouth'],
			'Take': ['This'],
			'Torpedo': ['Sunrise'],
			'Sacred': ['Mound'],
			'Mike': ['...'],
			'Real': [null],
			'Do': ['You', null],
			'Ample': ['Amour'],
			'Totem': [null],
			'Billionaire': ['and', 'Bachelors:'],
			'Lock,': ['Stock'],
			'Wives': [null],
			'Pastor': ['Feltbomb', 'of'],
			"Reese's": ['Wild'],
			'Mannequin': ['Depression', 'Mogul'],
			'Grim': ['Reader'],
			'Bodyguard': [null],
			'LeBronte': ['Towers'],
			'and': ['Ask', 'the', 'the', 'Donuts', 'Run', 'Jezabel', 'Bare', 'Remove', 'Nurses', 'Bone', 'Tuck', 'Deliver', 'Smolder', 'Coil', 'Nightingales', 'the', 'Narrow', 'Stardust', 'a', 'Cool', 'the', 'the', 'Sold!', 'the', 'the', 'the', 'Temporary', 'Death', 'the', 'Seek', 'Me', 'Mirrors', 'the'],
			'Spine': [null],
			'Detroit': [null],
			'Lightning': [null],
			"Anybody's": ['Dad'],
			"Rancher's": ['Heart'],
			'Splendor': [null],
			'Drops': ['of'],
			'Cottonwood': ['Tree'],
			'Fortress': [null],
			'Where': ['He'],
			'Slope': [null],
			'Bottomley,': ['Drunken'],
			'Over': ['Maine', 'Nowhere', 'the'],
			'One': ['Hot', null, 'And', 'Makes', 'Kiss', 'Reckless', 'Good'],
			'Babies': [null],
			"Queen's": ['Men'],
			'Then': ['Comes'],
			'Strip': ['Search'],
			'Wrangler,': ['Tender'],
			'Amour': [null],
			'Wager': [null],
			'Metalurgist’s': ['Widow'],
			'Lewd': ['Licorice'],
			"Highlander's": ['Touch'],
			'Seduction': [null, null, 'and'],
			'Least': ['Likely', 'Likely'],
			'About': ['a'],
			'Saint': ['Aphasia'],
			'Call': ['For', 'This'],
			'Cuzzi': [null],
			'Serene': [null],
			'Used': ['Man'],
			'a': ['Little', 'Dream', 'Salesman', 'Lady', 'Past', 'Man', 'Stranger', 'Lifetime', 'Tycoon', 'Man', 'Tycoon', 'Bride', 'Rebel', 'Daddy', "Rancher's", 'Moment', 'Wicked', 'Cowboy', 'Night', 'Lady', 'different', 'Spy', 'Thousand', 'Texan'],
			'Smiles': [null],
			'Investigations': [null],
			'Never': ['a'],
			'Wayward': [null],
			'Deliver': [null],
			'Santa': ['Claus'],
			'Proxy': [null],
			'Instinct': [null],
			'Honeysuckle': [null],
			'By': ['Moonlight', 'You', 'Mistake', 'Contract', 'Your', 'You'],
			'Temptress': [null],
			'Backwards': ['Honeymoon'],
			'Tawd': [null],
			'On': ['Crutches', 'the', 'the', 'My', 'Babies', 'Her', 'Twins'],
			'Potato': [null],
			'Prescription': ['For'],
			'Badly!': [null],
			'Silesian': ['Mornings'],
			'Contract': [null],
			'Tour': ['of'],
			'Feud': [null],
			'Coal': ['Tender'],
			'Budoir': [null],
			'Truly,': ['Madly'],
			'Saskatchewanton': ['Desire'],
			'Buffalo': ['Roman'],
			'Yours': ['for'],
			'Irish': ['Lace'],
			'Spawn': ['Shawn'],
			'Equator': [null],
			'Chez': ['Moi', 'Naïveté', 'Toupee'],
			'Driftwoody': [null],
			'Libby': ['Dough'],
			'Make-Believe': ['Mother'],
			'Sugarlips': [null],
			'Bosses': [null],
			'Kimono': [null],
			'Prenup': ['and'],
			'Persuasion': [null],
			'Got': ['Away', 'You,'],
			'Reckless': ['Night', 'Encounter'],
			'with': ['Max'],
			'Fanny': [null],
			'Someone': ['Knows'],
			"DON'T": ['Go'],
			'Scrotum': ['Totem'],
			'Bid': ['and'],
			"Devil's": ['Bargain', 'Bride'],
			'Hostage': [null],
			'Firenze': [null],
			'Virtue': [null],
			'Line': ['of'],
			'Dactyl': [null],
			'He': ['Belongs'],
			'Candide': ['Opal'],
			'Fleece': ['Panties'],
			'Attractors': [null],
			'Room': [null],
			'Dangerous': ['to'],
			'Cannery': ['Row'],
			'Faraway': ['Together'],
			"Hyde's": ['Assets'],
			'Raw': ['Ten'],
			'Huffington': ['Heights'],
			'Double': ['Wide', 'Exposure'],
			'Embrace': [null],
			'Pot': ['Luck'],
			'Battered': ['Rouge'],
			'Be': ['My', 'Mine'],
			'Loin': ['Lounger', 'Ranger'],
			'Lies': [null, null],
			'Turbine': ['Queen'],
			'Threshold': ['of'],
			'Captainstance': [null],
			'Ancient': [null],
			'Moan': [null],
			'Led': ['Astray'],
			'Wildest': ['Dreams'],
			'Gourmet': [null],
			'Long': ['Barleycorn'],
			'Heights': [null, null, null, null],
			'Leatherlust': [null],
			'Tickle': ['My'],
			'Donut': [null],
			'Dr.': ['Lov', 'Mantra', 'Princess', 'Truly', 'Irresistible', 'Jones', 'Desirable'],
			'Lost': ['My', 'Without'],
			'Mama': [null],
			'Poop': ['Nymph'],
			'Ball': ['Lightning'],
			'Hairy': ['Potter'],
			'Desires': [null],
			'Mystique': [null],
			'Here': ['Comes'],
			'Most': ['Eligible'],
			'above)': [null],
			'Peak': [null],
			'Condo': ['Mania'],
			'Alone': [null],
			'Exposure': [null],
			'Châteaux': ['Double'],
			'Jones': [null],
			'Kissing': ['Curmudgeons', 'Cousins'],
			'Anything': ['You', 'for'],
			'Patchwork': ['Guilt'],
			'So': ['Long', 'So', 'Toboso', 'Wicked'],
			'Curmudgeon': [null],
			'Nils': [null],
			'Undercover': ['Baby'],
			'Stakes': [null],
			'Vengeful': ['Groom'],
			'Heart': [null, null],
			'If': ['a', 'We'],
			'&': ['the', 'the', 'Page', 'Her', 'Videotape', 'Cranky', 'Deadly'],
			'Doing': ['Good'],
			'Sigh': ['Clone'],
			'Odor': [null],
			'Comfortable': ['Wife'],
			'Gentle': ['Purity'],
			'Sea': ['Quinn', 'Tan'],
			'M.D.': ['She'],
			'Moves': [null],
			'Faux': ['Fire'],
			'Tall,': ['Strong', 'Dark,', 'Dark,', 'Dark,'],
			'Juliet': ['and'],
			'Again': [null],
			'Indian': ['Summer'],
			'Eloquent': ['Silence'],
			'Sizzle!': [null],
			'Won': ['Ton'],
			'Digging': ['my'],
			'Passion': ['Planet', 'Pork', null, 'for', null, null, null],
			'Surprise': ['Family'],
			'Daughters': [null],
			'Risk': [null, null],
			'Chambermaid': ['Placemats'],
			'Gwyneth': [null],
			"Did?'": [null],
			'Romance?': [null],
			'Vera': [null],
			'Now': [null],
			'Not': ['My', 'Included'],
			"Lady's": ['Temptation'],
			'Pier': ['Deer'],
			'Adventurous': ['Bride'],
			'Flora': ['Fiona'],
			'Enemy': [null],
			'Reddish': ['Fetish'],
			'Paris': [null],
			'Helixer': [null],
			'Lost-and-Found': ['Groom'],
			'Knight': ['in'],
			'Remove': [null],
			'Convenience': [null],
			'Twice': ['in'],
			"Secretary's": ['Secret'],
			'Guilt': [null],
			'Vicky': [null],
			'Quick': ['Licks'],
			'Groin': [null],
			'Page': [null],
			'Major': ["Wycliff's"],
			'Taxi': ['Dance'],
			'Fondler': [null],
			'Shot': [null],
			'Sweet': ['Music', 'Gland', 'Lies', 'Rush', 'Savage'],
			'Obscene': ['Serene'],
			'Viking': [null],
			'Desirable': [null],
			'Souls': [null],
			'Pod': [null],
			'Go': [null],
			'Said,': ["'I", "'Surprise!'"],
			'Your': ['Wish', 'Touch', 'Pleasure?'],
			'Slow': ['Fever', 'Heat'],
			'Behaving': ['Badly!'],
			'Zone': [null],
			'From': ['My', 'There', 'My', '9'],
			'Suave': [null, null],
			'That’s': ['Not'],
			'Relations': [null],
			'Secret': ['Masochist', 'Wish', 'Agent', 'of', 'Virgin', null, null, 'Love-Child', null],
			'Zilla': ['On'],
			'Bee': [null],
			'Happy': ['Zygote'],
			"Housekeeper's": ['Daughter'],
			'You,': ['Babe'],
			'Recline': ['and'],
			'Answers': [null],
			'Romeo': ['On'],
			'Death': [null, null],
			'Mouth': [null],
			'Rebel': [null],
			'Suck': [null],
			'Coil': [null],
			'con': ['Valley'],
			'Trona': ['Love'],
			'Largemount': [null],
			'License': ['to'],
			'Opal': [null],
			'Follies': [null],
			'Left': ['Handed'],
			'Narrow': [null],
			'Came': ['C.O.D.'],
			'Panky': [null],
			'Pork': [null],
			'Maggie': [null, null],
			'Booty': [null, 'and', 'Base'],
			"Maverick's": ['Christmas'],
			'Spring': [null, null, 'and'],
			'Kisses': [null],
			'Back': ['To', 'in'],
			'Seed': [null, null],
			'Honey': ['Bee', 'Panty'],
			'Born': [null],
			'Girls': ['Do!'],
			'Girl': ['Who', 'Trouble'],
			'Bora': [null],
			'Cigars': ['and'],
			'Seek': [null],
			'Scandalous': ['Virtue'],
			'Akimbo': ['Arms'],
			'Candlelight': ['Virgil'],
			'Stocking': ['Stuffers'],
			'Deadly': [null],
			'Burgundy': [null],
			'Please': ['A', 'Remember'],
			'Hot': ['Duchess', 'Mama', 'Shot', 'on', 'on', 'on'],
			'How': ['To'],
			'Babes': ['In'],
			'Catfish': ['Cathouse'],
			'Gets': ['...'],
			'Mail-Order': ['Marriages'],
			'Woman': [null],
			'Dad': [null],
			"Trish's": ['Not-So-Little'],
			'Vegas': ['Heat', 'Heat', 'Sunrise', 'Rich'],
			'Glass': ['Curtain', 'Homes'],
			'Dote': [null],
			'Half': ['Full'],
			'ExoStorm': [null],
			'Day': ['to', 'In', null],
			'FistFire': [null],
			'Sucklings': [null],
			'Candy': [null],
			'Freud': ['to', null],
			'Muff': [null],
			'Night': ['of', null, null, null, null, null],
			'Silk,': ['Lace,'],
			'Courtney': ['Love'],
			'Comforts': [null],
			'MacAllister': ['Made'],
			'Intelligence': [null],
			'Poor': ['Trot'],
			'Tangle': [null],
			'Woods': [null],
			'List': [null],
			'Rising': [null],
			'Beauty': ['&', '&', null],
			'Woody': [null],
			'Happiness': [null],
			'Trot': ['of'],
			'Find': ['Out'],
			'Acacian': ['Spring'],
			'Planet': [null],
			'Only': [null, null, 'Thing', null],
			'Lot': [null],
			'Crack': [null],
			'Lov': [null],
			'Valley': [null],
			'Happened': ['on', 'At'],
			'Mary': ['Had', null],
			'Moisten': ['and'],
			'Accidental': ['Bride'],
			'C.O.D.': [null],
			'Jung': ['Wordsmiths'],
			'Sola': ['Menthe'],
			'Southern': ['Comforts'],
			'Rabid': [null],
			'Temptatious': [null],
			'Forever': ['Ecstasy'],
			"Smuggler's": ['Lady'],
			'Court': ['Odor'],
			'Last': ['Call', 'Cabaña', 'Santini', 'Virgin', 'of', 'Bachelor', 'Two', 'Chance'],
			'Menthe': [null],
			'Secrets': [null],
			'Despair': [null],
			'Tale': ['of'],
			'Smoke': ['and', 'and'],
			'Countess': [null],
			'Tall': ['Tales'],
			'Corporate': ['Wife'],
			'Waves': [null, 'Pushed'],
			'Astray': [null],
			'Oh': ['Jimmy'],
			'An': ['Arbor', 'Angel'],
			"Detective's": ['Undoing'],
			'Likely': ['Bride', 'to'],
			'Bloomers': [null],
			'Resist': ['a'],
			'Affair': [null],
			'Salty': ['Thursday'],
			'At': ['Midnight'],
			'Just': ['For', 'For', 'One', 'A', 'Like', 'a', 'Watch', 'Another'],
			'Chic': [null],
			'Sunrise': [null, null, null, null],
			'Irresistible': [null],
			'Tibbles': ['Interferes'],
			"Doesn't": ['Know'],
			'Darkness': [null],
			'Baby:': ['MacAllister'],
			'Baby?': [null],
			'Strange': ['Attractors'],
			'Marigold': ['Fairweather'],
			'Test': [null],
			'Tess': [null, null],
			"'I": ["Did?'"],
			'Baby,': ["DON'T"],
			'Thar': ['Hills'],
			'That': ['Summer', 'Boss'],
			'Rake': [null],
			"Annie's": ['Wild'],
			'Heir': ['of'],
			'Verde': [null],
			'Interferes': [null],
			'Austen’s': ['Bloomers'],
			'Aphasia': [null],
			'Know': [null],
			'Consequences': [null],
			'Lather': [null],
			'Than': ['Just', 'She', 'Chocolate'],
			'Cowboy': ['Prescribes', 'Be', null],
			'Pretend': ['Mistress'],
			'Michael': [null],
			'Naked': ['In'],
			'Truth': ['or'],
			'Marriage': ['Risk', 'Bed', 'Prize', null, null, 'on'],
			'Crotch': ['Bacon', 'Clover', 'Jockey'],
			'Mound': [null],
			'Salon': ['Da'],
			'Jimmy': [null],
			'Arousing': ['Consequences'],
			'Cute': [null],
			'Waltz': [null],
			'Scattered': ['Seed'],
			'Nefarious': ['Splendor'],
			'Fantasy': ['Pot', null],
			'Dough': [null],
			'9': ['to'],
			'Improperly': ['Pregnant'],
			'Lolita': ['Proud'],
			'Sanchica': ['de'],
			'Saucy': ['Sucklings'],
			'Elk': ['Flasher'],
			'Ovum': ['Trove'],
			'Winner': ['Gets'],
			'Spread': [null],
			'To': ['Eden', 'Trap', 'Marry', 'Please', 'Kiss', 'Burn'],
			'Secretion': [null],
			'Darling': [null, 'Cat'],
			'Bridal': ['Season'],
			'Caroline': [null],
			'Lord': ['of', 'of'],
			'Carolina': [null],
			'Baby.com': [null],
			'Season': [null],
			'August': ['Morning'],
			'Burn': [null],
			'at': ['the', 'the'],
			'Darls': [null],
			"Donovan's": ['Bed'],
			'Delight': [null, null],
			'Stew': [null],
			'Spouse': [null],
			'Sisters': [null],
			'my': ['Truffles'],
			'Dreamfeather': [null],
			'Remember': [null, 'This'],
			'Many': ['Bosses'],
			'Acid': [null],
			'Greased': ['Pilgrim'],
			'Monk': ['in'],
			'Thing': [null, 'Happened', 'Better'],
			'Virile': [null, 'Feral', 'Verde'],
			'Nothing!': [null],
			'Right': ['Now', null, 'Where'],
			'Agent': ['Groom'],
			'And': ['One', 'Me', 'The', 'the'],
			"Sister's": ['Baby'],
			'Duchess': ['On', null],
			'Sexiest': ['Mistake'],
			'Mountain': [null, null, null],
			'Cousins': [null],
			'Mood': ['Lantern'],
			'Place': ['to'],
			'Nightingales': [null],
			'Handed': ['General'],
			'Moon': ['Kathy', 'Milk', 'Over', 'Over', null],
			'Nick': ['All'],
			'Retro': ['Sin'],
			'Stowaway': [null],
			'Nurses': [null],
			'Bird': [null],
			'Eyes': ['of', 'Only'],
			'His': ['Arms', 'Choice', 'Very', 'Arch', 'Trail', 'Personal', 'Heels', 'Pretend', "Secretary's", 'Bride'],
			'Eastward': ['Frolic'],
			'Hit': ['and'],
			'Shawn': [null],
			'Cupcake': ['Queen'],
			'Lucky': [null],
			'Mania': [null],
			'Educating': ['Carolina'],
			'Malcontent': ['Wildebeest'],
			'Baby': [null, null, 'of', 'Trust', null, null, null, 'Lessons', null],
			'Pleasers': [null],
			'Herself': [null],
			'Made': [null],
			'Pregnant': ['Virgin', 'Princess'],
			'Pilgrim': [null],
			'Inside': [null],
			'Plain': ['Jayne'],
			'Patch': [null, 'Diaries'],
			'Morris': ['Oyster'],
			'Diamantra': [null],
			'Melodious': ['Malady'],
			'Flesh': ['Mistress', 'Sisters', null, null],
			'Freudian': ['Slipper', 'Slippers'],
			'Dance': [null],
			'Month': [null],
			'Ninety': ['Days'],
			'Quinn': [null],
			'Bitch': [null],
			'Tuck': [null],
			'Broadway': ['Dorian', 'Etiquette', 'Sanguine', 'Trotsky', 'Wellborne'],
			'Little': ['Secretion', 'Limb', 'Miss', 'Sex', 'Magic', 'Moonlighting'],
			'Bad': ['Vicky', 'Luck'],
			'...': ['Going', 'Wed!', 'Again', 'and', null, null, 'Married!'],
			'Takes': ['a', 'A', null],
			'Union': [null],
			'Marrying': ['Mike'],
			'Licorice': [null],
			'Spiral': ['Path'],
			'Charge': [null],
			'Tutor': [null],
			'Napa': [null],
			'Master': ['of'],
			'White': ['Light'],
			'Save': ['the'],
			'Taken': [null, 'By'],
			'Mother': [null, 'in', 'of'],
			'Hope': ['Grows'],
			'Yearlove': [null],
			'Kidnapping': ['His'],
			'à': ['Trois'],
			'Terms': ['of'],
			'Jessica': [null],
			'Sensora': [null],
			'She': ['Said', 'Had', 'Thinks', 'Takes', 'Makes', "Doesn't"],
			'Diet': ['Smiles'],
			'Crutches': [null],
			'Texas!': ['Lucky'],
			'Othello': [null],
			'Prisoner': ['of'],
			'Lap': ['Tiger', 'of'],
			'Stone': [null],
			'Salomé': ['Sandwich'],
			'Notorious': ['Groom'],
			'Daughter': ['of', null, null],
			'Lace,': ['&'],
			'Counter': ['Coy'],
			'Light': [null],
			'Holes': [null],
			'Juanita': [null],
			'Stand': [null],
			'Hearts': ['of'],
			'Reforming': ['A'],
			"'Surprise!'": [null],
			'Eyelash': ['Bouquet'],
			'Vaginasaurus': [null],
			'Reno': [null],
			'MR.': ['Stew'],
			'Demeanor': [null, null, null],
			'Measure': ['of'],
			'Sooth': [null],
			'Debt': ['to'],
			'Twig': [null],
			'Fiona': [null],
			'Said': [null],
			'Pink': ['Freud'],
			'Letters': [null],
			'Cyra-no-no': [null],
			'Tales': ['and'],
			'Feltbomb': [null],
			'Taming': ['a'],
			'Flowing': ['Ancient'],
			'Frolic': [null, 'Acid'],
			'than': ['the'],
			'Lonely': ['Blowfish'],
			'Lip': ['Frog'],
			'Claus': [null],
			'Fire': [null, null, null, null, 'Waltz', null, null, null, 'Inside', null],
			'Chocolate': ['Bondage', 'Budoir', null],
			'Proving': ['Herself'],
			'Music': ['Sweet', null],
			'Featherbaby': [null],
			'Rush': ['of'],
			'Prize': [null],
			'Steve': ['My'],
			'Determined': ['Groom'],
			'Youth': [null],
			'Billy': ['Brine'],
			'Groom': [null, 'Came', null, null, 'Who', null, null, null],
			'Daddy': [null, null, null],
			'I': ['Lost', 'Love', 'Got'],
			'Wandering': ['Dactyl', 'Gourmet'],
			'Drunken': ['Plumber'],
			'Charlie': [null],
			'Queen': ['Desire', null, null, null],
			'Fairweather': [null],
			'Scottish': ['Embrace'],
			'5': [null],
			"Enemy's": ['Daughter'],
			'Toklas': ['in'],
			'Maine': [null],
			'Tora': ['Tora', 'Bora'],
			'Caught': ['in', 'In'],
			'Cantina': [null],
			'Donuts': [null],
			'Very': ['Public', 'Own'],
			'We': ['Fall'],
			'Fever': [null],
			'Body': ['Contact'],
			'Booby': [null],
			'Megs': ['of'],
			'Beast': [null, null, null],
			'Merry': ['Widows'],
			'Mistress': [null, null, null, null, null],
			'Bean': ['Countess'],
			'Ghost': ['for'],
			'Masochist': [null],
			'Saddle': [null],
			'Together': [null, null],
			'Envoy': [null],
			'Golddiggers': [null],
			'Prior': ['Tease'],
			'Mistletoe': ['Mayhem'],
			'Pleasure': ["King's"],
			'Otherwise': ['Engaged'],
			'Wedding': ['Night', 'Ultimatum'],
			'Ducky': [null],
			'Flagrant': ['Miss'],
			'Julian': ['Strip'],
			'Spy': [null],
			'Cowgirls': [null],
			'Stardust': [null],
			'Angel': [null, null],
			'Wonderland': [null],
			'Pippy': ['Wrongstockings'],
			'Realm': ['of', null],
			'Virgil': [null, 'and'],
			'Defiant': ['Captive'],
			"World's": ['Most'],
			'Hester': ['Pure'],
			'Pagan': [null],
			'Secret-Agent': ['Sheik'],
			'Factor': [null],
			'Freud’s': ['Follies'],
			'Ton': [null],
			'Door': [null],
			'Stolen': ['Memories'],
			'Nobody': ['Does'],
			'Towers': [null, null],
			'Moi': [null],
			'Keister’s': ['Kiss'],
			'Mom': ['in', null],
			'Deuce': [null],
			'Captivity': [null],
			'Mod': ['Pod'],
			'Curtain': [null],
			'Dialed': [null],
			'Scholar': [null],
			'Cat': [null],
			'Ass-tronaut': [null],
			'Motherhood': ['Campaign'],
			'Real?': [null],
			'Can': ['Do'],
			'Flasher': [null],
			'Meet': [null],
			'Membrane': [null],
			'Madness': [null],
			'Lace': [null, null],
			'Honeymoon': [null],
			'Brine': [null],
			'Four': ['Men'],
			'Touch': ['Zone', 'of', 'of', null, 'So', null],
			'Open': ['Spouse', 'the', 'Spaces'],
			'Ian': ['Bottomley,', null],
			'Swan': [null],
			'Sex': ['on', 'Potato', null],
			"Man's": ['Baby'],
			'Edward': [null],
			'Beloved': ['Enemy'],
			'Salesman': [null],
			'Black': ['Velvet'],
			'Too': ['Late', 'Many', 'Wicked', 'Much'],
			'Contain': ['Her'],
			'Sandwich': [null],
			'Snail': [null],
			'Tempura': ['Sunrise'],
			'Closer': ['Than'],
			'Blame': ['It'],
			'Sheets': [null],
			'Lounger': [null],
			'the': ['Honey', 'Feast', 'Geese', 'Velvet', 'Beast', 'Whiled', 'Dog', 'Hostel', 'Toils', 'Blueberry', 'Time', 'Moonlight', 'Souls', 'Sheets', 'Cthulhu', 'Garden', 'Threshold', 'Kimono', 'Horizon', 'Ruffian', 'Alligator', 'Hun', 'Woods', 'Riviera', 'Date', 'Lawn', 'Shark', 'Snail', 'Virile', 'Cabaña', 'Cottonwood', 'Window', 'Yangtze', 'West', 'Dark', 'Vengeful', 'Marriage', 'Plain', 'Baby', 'Widow', 'Cowboy', 'Virgin', 'Wild', 'Joeville', 'Way', 'Delivery', 'Flesh', 'Wolf', 'above)', "Queen's", 'Pagan', 'Ruff', 'Witness', 'Wind', 'Line', 'Darkness', 'Day', 'Door', 'Bad,', 'Sexy', 'Bride', 'Winner', 'cover)'],
			'Article': ['of'],
			'Search': [null],
			'Tease': [null, null],
			'Pleasured': ['Lady'],
			'Hall': [null],
			'Roman': [null, 'Husband', 'Tess'],
			'Viking!': [null],
			'Lying': ['Eyes'],
			'Oulu': ['Rocinante'],
			"McKenna's": ['Bartered'],
			'Tropicava': [null],
			'General': [null],
			'Deer': [null],
			'Single': ['In'],
			'November': ['in'],
			'Ecstasy': [null, null],
			'Purity': [null],
			'Lifetime': [null],
			'Tempest': ['In'],
			'Arbor': ['Day'],
			'Sing': ['into'],
			'Space': [null],
			'Miles': ['Nils'],
			'de': ['Ville'],
			'Videotape': [null],
			'Crawfish': ['Cantina'],
			'Romance': [null],
			'Waiting': [null],
			'Subliminal': ['Aroma'],
			'Kitsch': ['Bitch'],
			"Cordina's": ['Crown'],
			'Tonic': [null],
			'Mornings': [null],
			'on': ['the', 'Dog', 'the', 'the', 'Trust', 'Approval', 'the', 'the', 'His', 'His', 'Demand', 'Her', 'the'],
			'March': [null],
			'Nuns': ['and'],
			'of': ['Clothing', 'Fire', 'Divine', 'Palm', 'the', 'Fire', 'Despair', 'My', 'World', 'the', 'Ryan', 'the', 'a', 'Time', 'Paris', 'a', 'the', 'Green', 'the', 'the', 'March', 'Judy', 'Engagement', 'Fire', 'a', 'Convenience', 'Black', 'Scandal', 'Passion', 'Sin', 'Mine', 'His', 'Desire', 'the', 'Possession', 'Substance', 'the', 'Passion', 'the', 'Scandal', 'Sin', 'My', 'a', 'Fire', 'Bradley', 'Luxury', 'the', "Raven's", 'the'],
			'Sold!': [null],
			'Cranky': [null],
			'Tiger': [null],
			'Kiss': [null, null, null, 'a'],
			'Qualm': ['Temptress'],
			'Bottleneck': ['Cafe'],
			'World': ['Domination'],
			'With': ['a', 'A'],
			'or': ['Dare'],
			'Littlest': ['Stowaway'],
			'Thrill': [null],
			'Wish': [null, 'Is'],
			'Bed': [null, null, null, null],
			'fulfilled.': [null],
			'Matre': ['Deviant'],
			'Proud': [null],
			'Guy': [null],
			'Slippers': [null],
			'Risky': ['Moves'],
			'Fiesto': [null],
			'Blind': ['Petunia'],
			'Office': ['Romance'],
			'Sorrel': ['Bell'],
			'Truly': [null],
			'Sheik': [null],
			'Penelope': ['Paj'],
			'Sympathy': ['Suck'],
			'Austen': ['Space'],
			'Carnal': ['Logic'],
			'Row': [null],
			'Texan': [null, null],
			'Babe': [null],
			'Hills': [null],
			'Interlude': [null],
			'Territorial': ['Bride'],
			'Much': ['Temptation'],
			'Kindergarten': ['Cupids'],
			'Practice': [null, 'Husband', 'Makes'],
			'Menàge': [null],
			'Prince': [null, 'Tool', null],
			'Texas': [null],
			'Final': ['Stand'],
			'Ass': ['Candy'],
			'Fiancée': ['By'],
			'Curmudgeons': [null],
			'Who': ['Took', '(Almost)', 'Will'],
			'Thyroid': ['Mary'],
			'Lawless': ['Ecstasy'],
			'Base': [null],
			'Spectacle': [null],
			'Aloha': ['Vera'],
			'Ask': ['Spread', 'Anyone'],
			'Trotsky': [null, null],
			'Friends': [null],
			'Lower': ['Pacific'],
			'Jayne': ['Bride'],
			'Wife': ['Degree', 'on', null, null, 'By', null, null],
			'Taking': ['On'],
			'Rutabaga': ['Darling', 'Princess'],
			'Uncovered': ['Passion'],
			'Comes': ['Santa', 'Marriage'],
			'Once': ['An'],
			'Dream': ['Trotter', null, 'Mountain'],
			'Juaneeda': ['Juanita'],
			'Ruffian': [null, 'of'],
			'Quilt': [null],
			'Love-Child': [null],
			'Frog': [null],
			'Taste': ['of', 'of'],
			'Dark,': ['and', '&', '&'],
			'Innocent?': [null],
			'Litter': [null],
			'Dorian': [null],
			'Captive': [null],
			'Cowboys': ['Are'],
			'Palm': ['Inc.'],
			'Are': ['for', 'You'],
			'Petunia': [null],
			'Proper': [null],
			'Best': ['Man'],
			'Barn': ['Booty', 'Spectacle'],
			'Combustion': [null],
			'Luv': [null],
			'Dancing': [null],
			'Memories': [null],
			'Pure': [null, 'Chance'],
			'Fireplace': [null],
			'Panty': [null],
			'You': [null, 'Take', 'Can', 'Call', null, 'For'],
			'Undoing': [null],
			'Stock': ['and'],
			'Grows': ['Fondler'],
			"Bachelor's": ['Bargain'],
			'Godzilla': ['In'],
			'Elvis': ['Othello'],
			'Domination': [null],
			'Valvestem': [null],
			'Trail': [null],
			'Enslaved': [null],
			'Messing': ['Around'],
			'Misconception': [null],
			'Cowboy?': [null],
			'Encounter': [null],
			'Crabs': [null],
			'Feral': ['Humans', null],
			'Ride': [null, null],
			'Zygote': [null],
			'Bridesmaid': [null],
			'Imprecious': [null],
			"Lookin'": ['for'],
			'Howling': ['In'],
			'Trap': ['a'],
			'Friendly': ['Fireplace'],
			'Lantern': [null],
			'Side': [null],
			'Bartered': ['Bride'],
			'Summer': [null, 'of', 'Thing'],
			'Bell': [null],
			'Oil': ['Patch'],
			'Marriages': [null],
			'Blues': [null],
			'Another': ["Man's", 'Day'],
			'Zizzy': ['Blue'],
			'Stand-In': [null],
			'Milk': [null],
			'Bathroom': [null],
			'Management': [null],
			'Devilette': [null],
			'Wed': [null, 'to'],
			'Tule': ['Elk'],
			'Fallow': [null],
			'Alligator': [null],
			'Caviar': ['Jack'],
			'Joeville': ['Loves'],
			'Late': ['for'],
			'Barebottom': ['Bob'],
			'Tremendulust': [null],
			'Odessa': [null],
			'Good,': ['the'],
			'Nights': [null],
			'Men': ['and', null],
			'Plex': [null],
			'Parvenu': ['Charlie'],
			'Innocence': [null, 'Undone', null],
			'California': [null, 'Caress'],
			'Salsa': ['Closet'],
			'Princess': [null, '&', 'Nest', 'Plex', 'Prawn', null, 'Is', null],
			'Brides,': ['No'],
			'Mineral': ['Spirits'],
			'Dolcinea': ['Interlude', 'Ladybird'],
			'Torrid': ['Temporary'],
			'Contact': [null],
			'Turn': [null, null],
			'Time': ['of', null, null],
			'The': ['Afirmable', 'Ass-tronaut', 'Catfish', 'Coal', 'Coming', 'Crawfish', 'Crustacean', 'Curmudgeon', 'Deuce', 'Fair', 'French', 'Grim', 'Hairy', 'Happy', 'Hole', 'Last', 'Left', 'Lollytart', 'Lowie', 'Lying', 'Malcontent', 'Metalurgist’s', 'Mist', 'Norse’s', 'Panky', 'Perfect', 'Poop', 'Secret', 'Straight', 'Tawd', 'Tule', 'Wandering', 'Wandering', 'Waves', 'Wellborne', "Boss's", 'Littlest', 'Marriage', 'Wife', 'Girl', 'Bride', "Librarian's", 'Measure', 'Blackmailed', 'Bride', 'Virgin', 'Last', 'Pregnant', 'Pleasure', 'Virgin', 'Adventurous', 'Baby', 'Groom', 'Boss', "Detective's", 'Determined', 'Groom', 'Billionaire', 'Ranger', 'Family', 'Reluctant', 'Least', 'Bad', 'Saddle', 'Twenty-Third', 'Merry', 'Motherhood', 'Way', 'Corporate', 'Millionaire', 'Father', 'M.D.', 'Accidental', 'Hunk', "Bachelor's", 'Marriage', 'Crowd', 'Notorious', 'Last', "Viking's", '$4.98', 'Bride', 'Secret', 'Virgin', 'Act', 'Bride', 'Beast', 'Husband', 'Cupcake', 'Older', 'Fire', 'Hellion', 'Spiral', 'Bridal', 'Pirate', 'Husband', 'Border', 'Virgin', "Highlander's", "Housekeeper's", 'Best', 'Only', "Groom's", 'Hotshot', 'Anonymous', 'Bride', 'Princess', "Devil's", 'Improperly', "Playboy's", 'Family', 'Man', 'Wedding', 'Secret', 'Last', 'Misconception', 'Mating', 'Good,', 'Last', 'Loner', "Nanny's"],
			'Mating': [null, 'of', 'Game'],
			'different': ['author'],
			"Passion's": ['Wild'],
			'Petting': ['the'],
			'Naughty': ['Towers'],
			'Is': ['My', 'My', 'Pregnant!'],
			'Pursuit': [null],
			'It': ['Better', 'All', 'Takes', 'On', 'Happened'],
			'Caress': [null, null],
			'High': ['Tide', 'Stakes'],
			'Pushed': ['Our'],
			'In': ['Detroit', 'Bed', 'the', 'My', 'the', 'Eden', 'The', 'Name', 'Death', 'The', 'My', 'Love?', 'the', 'Arms', 'Charge', 'the', 'Paradise', 'My'],
			'Something': ['Wild'],
			'Family': ['Practice', null, 'Way', 'Feud', null, 'Passions'],
			'Depression': [null],
			'Hostel': [null],
			'Passions': [null],
			'Blue': [null],
			'Approval': [null],
			'No': ['Groom'],
			'Velvet': ['Mauve', null],
			'Pleasure?': [null],
			"Raven's": ['Peak'],
			'Turn,': ['Turn'],
			'Panties': [null],
			'Suddenly': ['a'],
			'Lita': [null],
			'Bunny': ['Crack'],
			'Flight': ['Risk'],
			'Knows': [null],
			'Thousand': ['Nights'],
			'Hemline': ['of'],
			'Rules': ['of'],
			'Heat': ['Waves', null, 'in', null, null],
			'Delivery': ['Room'],
			'Diary': [null],
			'Trouble': ['Trove', null],
			'Dreams': ['fulfilled.', null],
			'Monica’s': ['Membrane'],
			'Max': [null],
			'Blowfish': [null],
			'Heaven': ['in', null, null],
			'Desire': [null, null, null, null, null, 'Me'],
			'Misty': ['August'],
			'Stranger': ['Proper', 'In', null, 'In'],
			'Like': ['Jessica'],
			'Marry': [null, null],
			'Married': ['to', 'For'],
			'This': ['Cowboy?', 'Romance?', null],
			'Ryan': [null],
			'Morning': [null, null],
			'Bargain': [null, null],
			'Micro': ['Menàge'],
			'Bachelors': [null],
			"She's": ['My'],
			'Inc.': [null],
			'Tycoon': [null, null],
			'Bomb': [null, null],
			'Playboy': ['in'],
			'Move': ['She'],
			'Zen': ['Doctor'],
			'Mission': [null],
			'Santini': ['Virgin'],
			'Hellion': ['Bride'],
			'Clone': [null],
			'Reluctant': ['Tutor', 'Mistress'],
			'Saphron': ['Sunrise'],
			'Jockey': [null],
			'B.': ['Toklas'],
			'Her': [null, null, 'Eyes', 'Bodyguard', 'Surprise', "Sister's", 'Passion', 'Wicked', 'Torrid', 'Pillow', 'Passionate', 'Perfect', 'Family', 'Tail'],
			'Monkey': ['Wrench'],
			'Father': [null, 'My', 'Factor'],
			'Three': [null, 'Brides,'],
			'Window': ['Pane'],
			'Straight': ['and'],
			'Breath': ['She', 'of'],
			'April': ['In'],
			'Dairy': ['Delight'],
			'Feather': ['From', 'Lace'],
			'Main': ['Man'],
			'Hem': ['in'],
			'Loving': ['Dare', null, 'Lies'],
			'Blueberry': ['Holes'],
			'Firefly': ['Friends'],
			'Smolder': [null],
			'Boss': ['and', 'of'],
			'Vicious': ['Suave'],
			'Bachelor': ['Blues', null],
			'Montana': ["Maverick's"],
			'Post': ['Oriface'],
			'Raspberry': [null],
			'Bronze': ['Mystique'],
			'Into': ['the'],
			'Contessa': ['Confessa'],
			'Older': ['Guy'],
			'Days': [null],
			'Whispers': [null],
			'Agenda': [null],
			'Keeps': [null],
			'Landmark': ['of'],
			'Wind': [null, null],
			'Personal': ['Relations', 'Agenda'],
			'Makes': ['Three', '(by', 'Perfect']
		};
		var keys = Object.keys(markovDict);
		var current = keys[Math.floor(Math.random()*keys.length)];
		var s = "";
		while (current != null){
			s += " " + current;
			nlist = markovDict[current];
			current = nlist[Math.floor(Math.random()*nlist.length)];
		}
		$('.romancegen').text(s)
	});
};
$(document).ready(main);
